import { useState } from 'react';
import { Copy, LockKeyhole, UnlockKeyhole } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import type { Game, Member } from '../lib/domain';
import type { RoomController } from '../lib/useRoom';
import { Alert, Button, Modal } from '../components/ui';
import { useApp } from '../lib/context';
export function Members({game:g,members,controller:c,mode,onClose}:{game:Game;members:Member[];controller:RoomController;mode:'local'|'cloud';onClose:()=>void}){const {toast}=useApp();const url=new URL('./',location.href.split('#')[0].split('?')[0]).href+`#/join?code=${g.code}`;return <Modal title="邀请与入座管理" wide onClose={onClose}><div className="stack">{mode==='local'?<Alert>这是本机主持模式，房间码不用于联网。各用手机领身份时，请回首页创建联机房间，或把本局导出后导入为联机副本。</Alert>:<><div className="invite"><div className="qr"><QRCodeSVG value={url} size={144} marginSize={3}/></div><div><small className="muted">邀请玩家申请加入</small><div className="room-code">{g.code}</div><div className="row"><Button onClick={async()=>{try{await navigator.clipboard.writeText(url);toast('邀请链接已复制');}catch{toast('复制未成功，请手动选择下方链接');}}}><Copy size={15}/> 复制邀请</Button><Button disabled={c.busy} onClick={()=>c.run('lock',{locked:!g.locked})}>{g.locked?<UnlockKeyhole size={15}/>:<LockKeyhole size={15}/>} {g.locked?'开放加入':'锁定房间'}</Button></div><input className="invite-url" readOnly value={url} onFocus={e=>e.target.select()} aria-label="邀请链接"/></div></div>{g.locked&&<Alert>房间已锁定，新的申请会被拒绝。已入座玩家可以继续重连。</Alert>}<h3>玩家申请与绑定</h3>{members.filter(m=>m.role==='player').length===0&&<p className="muted">还没有玩家申请。让玩家扫描二维码，等待批准。</p>}{members.filter(m=>m.role==='player').map(m=><MemberRow key={m.user_id} member={m} game={g} controller={c} members={members}/>)}</>}</div></Modal>;}
function MemberRow({member:m,game:g,controller:c,members}:{member:Member;game:Game;controller:RoomController;members:Member[]}){const available=g.seats.find(s=>!s.left&&!members.some(x=>x.status==='active'&&x.seat_id===s.id));const [seatId,setSeat]=useState(m.seat_id||available?.id||g.seats[0]?.id||''),[rebind,setRebind]=useState(false);return <div className="member-row"><div><strong>{m.nickname}</strong><small>{m.status==='active'?`已入座 · ${g.seats.find(s=>s.id===m.seat_id)?.index} 号`:m.status==='pending'?'等待批准':'已移除'}</small></div>{m.status==='active'?<Button variant="ghost" disabled={c.busy} onClick={()=>{if(confirm(`移除 ${m.nickname} 的访问权限？这不会改变座位身份。`))void c.member(m.user_id,'revoke');}}>移除权限</Button>:<div className="member-assign"><select value={seatId} onChange={e=>setSeat(e.target.value)}>{g.seats.filter(s=>!s.left).map(s=><option key={s.id} value={s.id}>{s.index}. {s.name}{members.some(x=>x.status==='active'&&x.seat_id===s.id)?'（已绑定）':''}</option>)}</select><label className="checkbox-row small"><input type="checkbox" checked={rebind} onChange={e=>setRebind(e.target.checked)}/> 替换该座位旧设备</label><Button variant="primary" disabled={c.busy||!seatId} onClick={async()=>{if(rebind&&!confirm(`确认把该座位重新绑定给 ${m.nickname}？旧设备将失去读取权限。`))return;if(await c.member(m.user_id,'approve',seatId,rebind))await c.run('seat',{id:seatId,patch:{name:m.nickname},reason:'批准玩家入座'});}}>批准入座</Button></div>}</div>;}
