import { useState } from 'react';
import { Eye, Send } from 'lucide-react';
import { grimoire, type Game, type GrimCard, type PrivateMessage } from '../lib/domain';
import type { Run } from '../lib/useRoom';
import { Alert, Button, Field, Modal, SeatChecks } from '../components/ui';
import { clock } from '../lib/storage';
export function GrimTable({seats}:{seats:GrimCard[]}){return <div className="table-scroll"><table><thead><tr><th>座位</th><th>角色</th><th>阵营</th><th>状态</th></tr></thead><tbody>{seats.map((s,i)=><tr key={i}><td>{s.index}. {s.name}</td><td>{s.role}{s.reminders.length>0&&<small className="gold block">{s.reminders.join(' · ')}</small>}</td><td className={s.alignment}>{s.alignment==='good'?'善良':'邪恶'}</td><td>{s.alive?'存活':'死亡'}</td></tr>)}</tbody></table></div>;}
export function MessageCard({message:m,children}:{message:PrivateMessage;children?:React.ReactNode}){return <article className="message-card"><div className="row between"><span>{m.kind==='choice'?'选择请求':m.kind==='grimoire'?'魔典快照':'说书人信息'}</span><small>{clock(m.at)} · 第 {m.round} 轮</small></div><p className="pre-wrap">{m.text}</p>{m.snapshot&&<GrimTable seats={m.snapshot}/>}<div className="message-response">{m.response!==null&&<span>已选择：{m.response.join('、')||'无'}</span>}</div>{children}</article>;}
export function MessageComposer({game:g,run,busy,onClose,initialSeat='',initialKind='info'}:{game:Game;run:Run;busy:boolean;onClose:()=>void;initialSeat?:string;initialKind?:'info'|'choice'|'grimoire'}){
 const [seatId,setSeatId]=useState(initialSeat||g.seats[0]?.id||''),[kind,setKind]=useState(initialKind),[text,setText]=useState(''),[options,setOptions]=useState(g.seats.filter(s=>!s.left).map(s=>`${s.index}. ${s.name}`).join('\n')),[min,setMin]=useState(1),[max,setMax]=useState(1),[seats,setSeats]=useState<string[]>(g.seats.map(s=>s.id)),[markers,setMarkers]=useState(false),[preview,setPreview]=useState(false);
 const target=g.seats.find(s=>s.id===seatId);const payload={seatId,kind,text,options:options.split('\n').map(s=>s.trim()).filter(Boolean),min,max,seats,withMarkers:markers};
 return <Modal wide={kind==='grimoire'} title={preview?'确认私密发送':'给玩家发送信息'} onClose={onClose} footer={preview?<><Button onClick={()=>setPreview(false)}>返回修改</Button><Button variant="primary" disabled={busy} onClick={async()=>{if(await run('message_send',payload))onClose();}}><Send size={16}/> 发送给 {target?.index} 号 {target?.name}</Button></>:<><Button onClick={onClose}>取消</Button><Button variant="primary" disabled={!seatId||(!text.trim()&&kind!=='grimoire')} onClick={()=>setPreview(true)}><Eye size={16}/> 预览发送内容</Button></>}><div className="stack">{preview?<><Alert>仅发送给 {target?.index} 号 {target?.name}。其他玩家不会收到此内容。</Alert><p className="pre-wrap">{text||'魔典快照'}</p>{kind==='choice'&&<><p>可选 {min}–{max} 项：</p><div className="chips">{payload.options.map((o,i)=><span className="chip" key={i}>{o}</span>)}</div></>}{kind==='grimoire'&&<GrimTable seats={grimoire(g,seats,markers)}/>}</>:<><Field label="收件人"><select value={seatId} onChange={e=>setSeatId(e.target.value)}>{g.seats.filter(s=>!s.left).map(s=><option key={s.id} value={s.id}>{s.index}. {s.name}</option>)}</select></Field><div className="tabs"><button className={kind==='info'?'active':''} onClick={()=>setKind('info')}>信息卡</button><button className={kind==='choice'?'active':''} onClick={()=>setKind('choice')}>选择请求</button><button className={kind==='grimoire'?'active':''} onClick={()=>setKind('grimoire')}>魔典快照</button></div><Field label="告知内容"><textarea value={text} onChange={e=>setText(e.target.value)} rows={4} maxLength={2000} placeholder="写下这位玩家现在应该获知的信息…"/></Field>{kind==='info'&&<div className="chips">{['0','1','2','3','是','否','善良','邪恶'].map(x=><button key={x} className="chip" onClick={()=>setText(x)}>{x}</button>)}</div>}{kind==='choice'&&<><Field label="可选项（每行一项）"><textarea rows={6} value={options} onChange={e=>setOptions(e.target.value)}/></Field><div className="form-grid"><Field label="最少选择"><input type="number" min={0} max={20} value={min} onChange={e=>setMin(Number(e.target.value))}/></Field><Field label="最多选择"><input type="number" min={1} max={20} value={max} onChange={e=>setMax(Number(e.target.value))}/></Field></div></>}{kind==='grimoire'&&<><Alert>选择允许展示的座位。快照不包含自由笔记、历史私信和操作日志。</Alert><SeatChecks seats={g.seats} selected={seats} onChange={setSeats}/><label className="checkbox-row"><input type="checkbox" checked={markers} onChange={e=>setMarkers(e.target.checked)}/> 同时展示这些座位的提醒标记</label></>}</>}</div></Modal>;
}
