import { artUrl } from '../lib/art';
import { useEffect, useState } from 'react';
import { BookOpen, Eye, EyeOff, LockKeyhole, MessageSquare, NotebookPen, Users } from 'lucide-react';
import type { PersonalView, PrivateMessage, PublicGame, Timer } from '../lib/domain';
import type { Run } from '../lib/useRoom';
import { Alert, Button, Empty, RoleToken, ScriptRead } from '../components/ui';
import { TownBoard } from '../components/TownBoard';
import { GrimTable, MessageCard } from './Messages';
import { clock, download, phaseLabel } from '../lib/storage';
import { serverNow } from '../lib/supabase';
import { RoomNotes } from './Notes';
export function PublicTown({room:r,exit}:{room:PublicGame;exit?:()=>void}){return <div className="public-page"><div className="section-heading"><div><h1>{r.title}</h1><p>公开城镇 · {phaseLabel(r.phase,r.round)}</p><PublicTimer timer={r.timer}/></div>{exit&&<Button onClick={exit}>返回说书人</Button>}</div>{r.paused&&<Alert>说书人暂停了对局。</Alert>}<div className="chips">{(r.fabled??[]).map(role=><span className="chip gold" key={role.id} title={role.ability}>{role.name}</span>)}</div><TownBoard seats={r.seats.map(s=>({...s,role:s.role?.name}))} phase={r.phase} round={r.round} winner={r.winner}/><details className="public-events"><summary>城镇公告（{r.events.length}）</summary>{r.events.slice(-12).reverse().map(e=><p key={e.id}><time>{clock(e.at)}</time>{e.text}</p>)}</details>{r.review&&<section className="published-review"><h2>说书人复盘</h2><p className="pre-wrap">{r.review.text}</p><GrimTable seats={r.review.seats}/><Button onClick={()=>download(`${r.title}_公开复盘.json`,{kind:'public',room:r})}>导出公开复盘</Button></section>}</div>;}
export function Player({room:r,personal:p,run,busy}:{room:PublicGame;personal:PersonalView;run:Run;busy:boolean}){const [tab,setTab]=useState('card'),[revealed,setRevealed]=useState(false);const me=r.seats.find(s=>s.id===p.seatId);const unread=p.messages.filter(m=>!m.seen).length;
 useEffect(()=>{setRevealed(false);},[p.cardVersion]);
 useEffect(()=>{const hide=()=>{setRevealed(false);setTab(t=>t==='messages'?'card':t);};window.addEventListener('blur',hide);document.addEventListener('visibilitychange',hide);return ()=>{window.removeEventListener('blur',hide);document.removeEventListener('visibilitychange',hide);};},[]);
 useEffect(()=>{if(!revealed)return;const timer=setTimeout(()=>setRevealed(false),30000);return ()=>clearTimeout(timer);},[revealed]);
 return <main className="player-page"><header className="player-heading"><div><small>{r.title} · {phaseLabel(r.phase,r.round)}</small><PublicTimer timer={r.timer}/><h1>{me?.name||'玩家'}，欢迎来到城镇。</h1></div><span className="player-seat">{String(me?.index||0).padStart(2,'0')}<small>号座位</small></span></header>{r.paused&&<Alert>对局已暂停，请等待说书人。</Alert>}<nav className="player-tabs">{[['card','我的身份',LockKeyhole],['town','公开城镇',Users],['messages','私密信息',MessageSquare],['script','剧本',BookOpen],['notes','私人笔记',NotebookPen]].map(([id,label,Icon]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setRevealed(false);}}><Icon size={18}/><span>{label}{id==='messages'&&unread>0&&<b>{unread}</b>}</span></button>)}</nav>{tab==='card'?<div className="identity-stage">{!p.role?<Empty title="等待说书人发身份">入座已确认。说书人完成配置后，你的身份卡会出现在这里。</Empty>:<><div className={`identity-card ${revealed?'revealed':''}`}>{revealed?<><RoleToken role={p.role} alignment={p.alignment||undefined}/><span className={p.alignment||''}>{p.alignment==='good'?'善良阵营':'邪恶阵营'}</span><h2>{p.role.name}</h2><p>{p.role.ability}</p><small>{me?.index} 号 · {me?.name}</small></>:<><img className="identity-back-art" src={artUrl('art/cards/identity-back.webp')} alt="" width={88} height={124}/><h2>你的故事，暂时保密。</h2><p>确认身边没人能看见屏幕后<br/>再揭开属于你的身份。</p></>}</div><Button variant={revealed?'secondary':'primary'} disabled={busy} onClick={()=>{if(!revealed){setRevealed(true);void run('ack_card');}else setRevealed(false);}}>{revealed?<EyeOff size={18}/>:<Eye size={18}/>} {revealed?'遮住身份':'查看我的身份'}</Button><p className="muted small">切出页面或 30 秒后自动遮住身份。</p>{p.cardVersion>1&&p.acknowledged<p.cardVersion&&<Alert>说书人更新了你的身份信息，请重新查看。</Alert>}</>}</div>:tab==='town'?<PublicTown room={r}/>:tab==='script'?<div className="player-content"><ScriptRead script={r.script}/></div>:tab==='notes'?<RoomNotes room={r} mySeatId={p.seatId}/>:<div className="player-content inbox"><h2>说书人的私密信息</h2><p className="muted">这些内容只有你和说书人可见。</p>{p.messages.length===0?<Empty title="还没有新信息">轮到你的夜间行动时，说书人可以在这里与你沟通。</Empty>:p.messages.slice().reverse().map(m=><MessageCard key={m.id} message={m}>{m.kind==='choice'&&m.response===null?<PlayerResponse message={m} run={run} busy={busy}/>:!m.seen?<Button disabled={busy} onClick={()=>run('ack_message',{id:m.id})}>我已阅读</Button>:<small className="muted">已阅读</small>}</MessageCard>)}</div>}</main>;
}
function PlayerResponse({message:m,run,busy}:{message:PrivateMessage;run:Run;busy:boolean}){const [chosen,setChosen]=useState<string[]>([]);return <div className="stack"><small className="muted">请选择 {m.min}–{m.max} 项；提交后如需更改，请联系说书人。</small><div className="choice-options">{m.options.map(o=><label className={`choice-option ${chosen.includes(o)?'selected':''}`} key={o}><input type={m.max===1?'radio':'checkbox'} name={`choice-${m.id}`} checked={chosen.includes(o)} onChange={()=>setChosen(chosen.includes(o)?chosen.filter(x=>x!==o):m.max===1?[o]:[...chosen,o])}/>{o}</label>)}</div><Button variant="primary" disabled={busy||chosen.length<m.min||chosen.length>m.max} onClick={()=>run('respond',{id:m.id,response:chosen})}>确认提交选择</Button></div>;}
function PublicTimer({timer}:{timer:Timer}){const [now,setNow]=useState(serverNow);useEffect(()=>{const id=setInterval(()=>setNow(serverNow()),1000);return ()=>clearInterval(id);},[]);if(!timer.endsAt&&!timer.remaining)return null;const seconds=Math.ceil(Math.max(0,timer.endsAt?timer.endsAt-now:timer.remaining)/1000);return <span className="public-timer">讨论计时 {String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}{!timer.endsAt?' · 已暂停':''}</span>;}

