import { RoleForm } from '../components/RoleForm';
import { ScriptImageImport } from './ScriptImageImport';
import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Download, FileUp, ImagePlus, MoreHorizontal, Plus, Search, Settings2, Trash2, Users, FileText } from 'lucide-react';
import { useApp } from '../lib/context';
import { BASE_SCRIPTS, CATALOG, TEAM_LABELS, TEAMS, copyScript, exportScript, importScript, scriptWarnings, uid, type Role, type Script, type Team } from '../lib/domain';
import { download, navigate, readFile } from '../lib/storage';
import { Alert, Button, Field, Modal, RoleInfo, RoleToken, ScriptBadge, TeamBadge } from '../components/ui';
type WorkshopView='overview'|'library'|'roles'|'add'|'details'|'tools';
export function Scripts({initial,onApply,onClose}:{initial?:Script;onApply?:(s:Script)=>Promise<boolean>;onClose?:()=>void}){
 const {scripts,saveScript,deleteScript,toast}=useApp();
 const [script,setScript]=useState<Script>(()=>initial?copyScript(initial):copyScript(scripts.find(s=>s.id===localStorage.getItem('bt-selected-script'))||BASE_SCRIPTS[0]));
 const customOriginal=useRef<string|null>(null);
 const baseline=useRef(JSON.stringify(script));const dirty=JSON.stringify(script)!==baseline.current;
 const [view,setView]=useState<WorkshopView>('overview'),[imageImport,setImageImport]=useState(false),[search,setSearch]=useState(''),[librarySearch,setLibrarySearch]=useState(''),[team,setTeam]=useState<Team>('townsfolk'),[limit,setLimit]=useState(24);
 const [creating,setCreating]=useState(false),[newName,setNewName]=useState('');
 const [warnings,setWarnings]=useState<string[]>([]),[error,setError]=useState(''),[custom,setCustom]=useState<Role|null>(null),[info,setInfo]=useState<Role|null>(null),[busy,setBusy]=useState(false);const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 const catalog=useMemo(()=>{const map=new Map(CATALOG.map(r=>[r.id,r]));scripts.forEach(s=>s.roles.filter(r=>r.custom).forEach(r=>map.set(r.id,r)));script.roles.forEach(r=>map.set(r.id,r));return [...map.values()];},[scripts,script.roles]);
 const selected=new Set(script.roles.map(r=>r.id));
 const list=(view==='add'?catalog:script.roles).filter(r=>r.team===team&&`${r.name} ${r.id} ${r.ability}`.toLowerCase().includes(search.trim().toLowerCase()));
 const checks=[...scriptWarnings(script),...warnings];
 function open(next:WorkshopView){setView(next);setError('');setSearch('');setLimit(24);window.scrollTo({top:0});}
 function replace(next:Script,imported=false){if(dirty&&!confirm('当前修改尚未保存，确定替换当前剧本？'))return false;baseline.current=imported?'':JSON.stringify(next);setScript(next);setWarnings([]);open('overview');return true;}
 function startNew(){setNewName('');setCreating(true);}
 function createNew(){if(replace({...copyScript(BASE_SCRIPTS[0]),name:newName.trim()||'未命名剧本',author:'',description:'',roles:[],extras:[]},true)){setCreating(false);setTeam('townsfolk');open('add');}}
 const toggle=(r:Role)=>setScript(s=>({...s,roles:s.roles.some(x=>x.id===r.id)?s.roles.filter(x=>x.id!==r.id):[...s.roles,structuredClone(r)],extras:s.roles.some(x=>x.id===r.id)?s.extras.filter(x=>!(x&&typeof x==='object'&&(x as {id?:string}).id===r.id)):s.extras}));
 async function save(use=false){if(busy)return;setBusy(true);setError('');try{if(!script.roles.length)throw new Error('请至少保留一个角色。');const next={...script,name:script.name.trim()||'未命名剧本',version:script.version+1,updatedAt:new Date().toISOString()};await saveScript(next);baseline.current=JSON.stringify(next);setScript(next);if(use){if(onApply){if(await onApply(next))onClose?.();}else{localStorage.setItem('bt-selected-script',next.id);navigate('/');}}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(f?:File){if(!f)return;try{const result=importScript(await readFile(f,2_000_000));if(replace(result.script,true)){setWarnings(result.warnings);toast('剧本已导入，请核对后保存');}}catch(e){setError((e as Error).message);}}
 const freshRole:Role={id:`custom_${uid().slice(0,8)}`,name:'',team:'townsfolk',ability:'',firstNight:0,otherNight:0,reminders:[],custom:true};
 const titles:Record<WorkshopView,string>={overview:'剧本工坊',library:'选择剧本',roles:'角色配置',add:'添加角色',details:'剧本资料',tools:'更多工具'};
 return <div className={`page script-editor workshop ${initial?'embedded':''}`}>
 <header className="workshop-header">{view!=='overview'&&<Button variant="ghost" aria-label="返回" onClick={()=>open(view==='add'?'roles':'overview')}><ArrowLeft size={22}/></Button>}<h1>{titles[view]}</h1>{view==='overview'&&<Button variant="ghost" aria-label="更多工具" onClick={()=>open('tools')}><MoreHorizontal size={26}/></Button>}</header>
 <input ref={file} type="file" accept="application/json,.json" hidden onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/>
 {error&&<Alert kind="error">{error}</Alert>}
 {view==='overview'&&<>
 <section className="workshop-scene"><ScriptBadge script={script} size={48}/><div><h2>{script.name||'未命名剧本'}</h2><p>{script.roles.length} 个角色{dirty?' · 未保存':' · 已载入'}</p></div><Button onClick={()=>open('library')}>更换剧本</Button></section>
 <div className="workshop-quick"><Button onClick={startNew}><Plus size={18}/> 新建剧本</Button><Button onClick={()=>open('library')}>我的剧本 / 基础剧本</Button></div><div className="workshop-menu"><button onClick={()=>{setTeam('townsfolk');open('roles')}}><Users/><span><strong>角色配置</strong><small>查看、添加或移除角色</small></span><ChevronRight/></button><button onClick={()=>open('details')}><FileText/><span><strong>剧本资料</strong><small>名称、作者与简介</small></span><ChevronRight/></button></div>
 {checks.length>0&&<details className="workshop-checks"><summary>查看 {checks.length} 条剧本提示</summary>{checks.map((w,i)=><p key={i}>{w}</p>)}</details>}
 <div className="workshop-save"><Button disabled={busy} onClick={()=>save()}>保存剧本</Button><Button variant="primary" disabled={busy} onClick={()=>save(true)}>{onApply?'应用到本局':'用此剧本开局'}</Button></div>
 </>}
 {view==='library'&&<><div className="search-field"><Search size={20}/><input aria-label="搜索剧本" placeholder="搜索剧本名称" value={librarySearch} onChange={e=>setLibrarySearch(e.target.value)}/></div><h2 className="workshop-subtitle">基础剧本</h2><div className="workshop-library">{BASE_SCRIPTS.filter(s=>s.name.includes(librarySearch.trim())).map(s=><button key={s.id} onClick={()=>replace(copyScript(s))}><ScriptBadge script={s} size={64}/><strong>{s.name}</strong><small>{s.roles.length} 个角色</small></button>)}</div><h2 className="workshop-subtitle">我的剧本</h2><div className="workshop-saved">{scripts.filter(s=>!['tb','bmr','snv'].includes(s.id)&&s.name.includes(librarySearch.trim())).map(s=><div key={s.id}><button onClick={()=>replace(structuredClone(s))}><ScriptBadge script={s} size={32}/><span><strong>{s.name}</strong><small>{s.roles.length} 个角色</small></span><ChevronRight size={20}/></button><Button variant="ghost" aria-label={`删除${s.name}`} onClick={async()=>{if(confirm(`删除已保存的“${s.name}”？当前编辑内容和已开局快照不受影响。`)){try{await deleteScript(s.id);}catch(e){setError((e as Error).message);}}}}><Trash2 size={20}/></Button></div>)}</div>{!scripts.some(s=>!['tb','bmr','snv'].includes(s.id)&&s.name.includes(librarySearch.trim()))&&<p className="muted">暂无匹配的已保存剧本</p>}<Button className="full" onClick={startNew}><Plus size={20}/> 新建空白剧本</Button></>}
 {(view==='roles'||view==='add')&&<>
 <div className="workshop-selection"><span>{script.name}<small>{dirty?'未保存':'已载入'}</small></span><strong>已选 {script.roles.length} 个角色</strong></div>
 <section className="workshop-selected-list" aria-label="已选角色名单">
 {!script.roles.length?<p>暂未添加角色，在下方挑选后会直接显示在这里。</p>:TEAMS.map(t=>{const roles=script.roles.filter(r=>r.team===t);return roles.length>0&&<div className="workshop-selected-row" key={t}><h3><TeamBadge team={t} size={16}/>{TEAM_LABELS[t]}<small>{roles.length}</small></h3><ul>{roles.map(r=><li key={r.id}><button onClick={()=>setInfo(r)} aria-label={`查看已选角色${r.name}`}><RoleToken small role={r}/>{r.name}</button><button className="remove-selected" onClick={()=>toggle(r)} aria-label={`从已选名单移除${r.name}`}>×</button></li>)}</ul></div>;})}
 </section>
 <div className="workshop-role-heading"><p>{view==='roles'?`${script.roles.length} 个已选角色 · 点头像查看能力`:'按类别选择，或搜索角色名称'}</p>{view==='add'&&<Button onClick={()=>{customOriginal.current=null;setCustom({...freshRole,team})}}><Plus size={18}/> 创建角色</Button>}{view==='roles'&&<Button onClick={()=>open('add')}><Plus size={20}/> 添加角色</Button>}</div>
 <div className="workshop-teams">{TEAMS.map(t=><button key={t} className={team===t?'active':''} aria-pressed={team===t} onClick={()=>{setTeam(t);setLimit(24);setSearch('')}}>{TEAM_LABELS[t]}<small>{script.roles.filter(r=>r.team===t).length}</small></button>)}</div>
 <div className="search-field"><Search size={20}/><input aria-label="搜索角色" placeholder={`搜索${TEAM_LABELS[team]}角色`} value={search} onChange={e=>{setSearch(e.target.value);setLimit(24)}}/></div>
 <div className="workshop-roles">{list.slice(0,limit).map(r=><div key={r.id} className={selected.has(r.id)?'picked':''}><button className="workshop-role" onClick={()=>setInfo(r)}><RoleToken role={r}/><strong>{r.name}</strong>{r.unresolved&&<small>待补全</small>}</button>{view==='add'&&<Button variant="ghost" aria-label={selected.has(r.id)?`移除${r.name}`:`添加${r.name}`} onClick={()=>toggle(r)}>{selected.has(r.id)?<Check size={19}/>:<Plus size={19}/>} {selected.has(r.id)?'已选':'添加'}</Button>}</div>)}</div>
 {!list.length&&<p className="workshop-empty">{view==='roles'?'此类别还没有角色，可点“添加角色”。':'没有找到角色，试试其他名称或类别。'}</p>}
 {list.length>limit&&<Button className="full" onClick={()=>setLimit(n=>n+24)}>再显示 24 个</Button>}
 {view==='add'&&<div className="workshop-add-footer"><Button variant="primary" onClick={()=>open('overview')}>完成选角（{script.roles.length}）</Button></div>}
 </>}
 {view==='details'&&<div className="stack workshop-details"><Field label="剧本名称"><input value={script.name} maxLength={100} onChange={e=>setScript({...script,name:e.target.value})}/></Field><Field label="作者"><input value={script.author} maxLength={100} onChange={e=>setScript({...script,author:e.target.value})}/></Field><Field label="简介"><textarea rows={4} maxLength={500} value={script.description} onChange={e=>setScript({...script,description:e.target.value})}/></Field><Button variant="primary" onClick={()=>open('overview')}>完成编辑</Button></div>}
 {view==='tools'&&<div className="workshop-menu"><button onClick={()=>setImageImport(true)}><ImagePlus/><span><strong>图片转 JSON</strong><small>识别剧本图片，核对后导入</small></span><ChevronRight/></button><button onClick={()=>file.current?.click()}><FileUp/><span><strong>导入 JSON</strong><small>打开已有的剧本文件</small></span><ChevronRight/></button><button onClick={()=>download(`${script.name||'剧本'}.json`,exportScript(script),true)}><Download/><span><strong>导出 JSON</strong><small>下载当前编辑的剧本</small></span><ChevronRight/></button><button onClick={startNew}><Plus/><span><strong>新建空白剧本</strong><small>从零开始挑选角色</small></span><ChevronRight/></button></div>}
 {creating&&<Modal title="新建剧本" onClose={()=>setCreating(false)} footer={<><Button onClick={()=>setCreating(false)}>取消</Button><Button variant="primary" onClick={createNew}>下一步：添加角色</Button></>}><form onSubmit={e=>{e.preventDefault();createNew();}}><Field label="剧本名称"><input autoFocus placeholder="可不填，默认：未命名剧本" maxLength={100} value={newName} onChange={e=>setNewName(e.target.value)}/></Field><p className="muted">作者和简介可稍后在“剧本资料”中补充。</p></form></Modal>}
 {imageImport&&<ScriptImageImport catalog={catalog} onClose={()=>setImageImport(false)} onImport={next=>{if(replace(next,true)){setImageImport(false);toast('图片剧本已放入工坊，请核对后保存');}}}/>}
 {info&&<Modal title="角色资料" onClose={()=>setInfo(null)} footer={<><Button onClick={()=>{customOriginal.current=info.id;setCustom({...structuredClone(info),custom:true});setInfo(null)}}><Settings2 size={18}/> 编辑角色</Button><Button onClick={()=>{toggle(info);setInfo(null)}}>{selected.has(info.id)?'从剧本移除':'加入剧本'}</Button></>}><RoleInfo role={info}/></Modal>}
 {custom&&<RoleForm role={custom} takenIds={script.roles.filter(r=>r.id!==customOriginal.current).map(r=>r.id)} onClose={()=>setCustom(null)} onSave={r=>{setScript(s=>({...s,roles:[...s.roles.filter(x=>x.id!==r.id&&x.id!==customOriginal.current),r],extras:customOriginal.current&&customOriginal.current!==r.id?s.extras.filter(x=>!(x&&typeof x==='object'&&(x as {id?:string}).id===customOriginal.current)):s.extras}));setTeam(r.team);setCustom(null)}}/>}
 </div>;
}
