import { useState } from 'react';
import { ArrowRight, CircleHelp, Dices, Plus, Send, Users } from 'lucide-react';
import { availableTravellerRoles, baseCounts, defaultAlignment, findRole, setupIssues, TEAM_LABELS, type Game, type Script, type Seat } from '../lib/domain';
import { TownBoard } from '../components/TownBoard';
import type { Run } from '../lib/useRoom';
import { Alert, Button, Field, Modal, RoleSelect, RoleToken } from '../components/ui';
export function Setup({game:g,run,busy,onScript,onMembers}:{game:Game;run:Run;busy:boolean;onScript:()=>void;onMembers:()=>void}){
 const normal=g.seats.filter(s=>!s.traveller).length;
 const [counts,setCounts]=useState(baseCounts(normal)),[deal,setDeal]=useState(false),[random,setRandom]=useState(true),[traveller,setTraveller]=useState(false),[selected,setSelected]=useState<string>();
 const issues=setupIssues(g);
 const selectedSeat=g.seats.find(s=>s.id===selected);
 return <div className="setup-page">
  <h1 className="setup-title">准备对局</h1>
  <div className="setup-controls">
   <div className="setup-script"><small>本局剧本</small><strong>{g.script.name}</strong><Button variant="ghost" onClick={onScript}>换剧本 <ArrowRight size={15}/></Button></div>
   <Field label="普通玩家人数"><select disabled={busy} value={normal} onChange={e=>{const count=Number(e.target.value);setCounts(baseCounts(count));void run('resize',{count});}}>{Array.from({length:11},(_,i)=>i+5).map(n=><option key={n} value={n}>{n} 人</option>)}</select></Field>
  </div>
  <div className="setup-table-actions"><Button onClick={onMembers}><Users size={17}/> 管理入座</Button><Button disabled={busy} onClick={()=>run('auto_setup',{counts})}><Dices size={17}/> 随机配牌</Button><Button onClick={()=>setTraveller(true)} disabled={busy}><Plus size={17}/> 旅行者</Button></div>
  <p className="muted small setup-table-hint">点座位，修改昵称与身份</p>
  <TownBoard phase={g.phase} round={g.round} selected={selected} onSelect={setSelected} seats={g.seats.map(s=>({...s,role:findRole(g.script,s.roleId)?.name||'待配角色',roleData:findRole(g.script,s.roleId)}))}/>
  <details className="setup-help setup-advanced"><summary><CircleHelp size={20}/> 配牌设置{issues.length>0?` · ${issues.length} 项待补全`:""}</summary>
   {issues.length>0&&<div className="issues"><h3>待补全项目</h3>{issues.map((m,i)=><p key={i}>{m}</p>)}</div>}<div className="bag-config"><div><h3>角色配比</h3><p>特殊角色的配比请手动调整，再随机选角色。</p></div><div className="count-inputs">{(['townsfolk','outsider','minion','demon'] as const).map((t,i)=><Field label={TEAM_LABELS[t]} key={t}><input type="number" disabled={busy} min={0} max={15} value={counts[i]} onChange={e=>setCounts(counts.map((n,j)=>j===i?Number(e.target.value):n))}/></Field>)}</div></div>
   <Alert>角色池表示“可能出现的身份”。每个座位配置的角色才会入袋；“展示身份”单独控制玩家收到的卡片。酒鬼请展示为镇民。</Alert>
   <FabledRules game={g} run={run} busy={busy}/>
   <div className="bluff-config"><h3>恶魔伪装</h3><p className="muted">至多 3 个未入场善良角色；不会自动发送，请在首夜确认后发给恶魔。</p><div className="form-grid three">{[0,1,2].map(i=><RoleSelect key={i} roles={g.script.roles.filter(r=>['townsfolk','outsider'].includes(r.team))} value={g.bluffs[i]||''} onChange={id=>{const next=[...g.bluffs];next[i]=id;void run('bluffs',{roles:next.filter(Boolean)});}} disabled={busy}/>)}</div>{g.bluffs.some(id=>g.seats.some(s=>s.roleId===id||s.shownRoleId===id))&&<p className="hint">所选伪装与在场 / 展示角色重叠，请核对。</p>}</div>
  </details>
  <div className="setup-footer"><div><strong>{g.seats.filter(s=>s.roleId).length} / {g.seats.length} 个座位已配好</strong><p>{issues.length?`${issues.length} 项配置需要补全`:'配置完整，可进入发牌确认'}</p></div><Button variant="primary" disabled={busy||issues.length>0} onClick={()=>setDeal(true)}><Send size={17}/> 确认并发身份</Button></div>{deal&&<Modal title="确认本局身份" onClose={()=>setDeal(false)} footer={<><Button onClick={()=>setDeal(false)}>继续调整</Button><Button variant="primary" disabled={busy} onClick={async()=>{if(await run('deal',{shuffle:random}))setDeal(false);}}>发身份，开始第 1 夜</Button></>}><div className="stack"><Alert>本次操作会锁定角色分配。玩家获得的是“展示身份”；真实身份只保存在说书人魔典中。</Alert><label className="checkbox-row"><input type="checkbox" checked={random} onChange={e=>setRandom(e.target.checked)}/> 将普通玩家的身份组合随机分配到座位</label><small className="muted">取消勾选则保持当前逐座位分配。旅行者不参加随机分配。</small><div className="deal-summary">{g.seats.map(s=><div key={s.id}><span>{s.index}. {s.name}</span><strong>{findRole(g.script,s.roleId)?.name}</strong><span className="muted">展示：{findRole(g.script,s.shownRoleId)?.name} / {s.shownAlignment==='good'?'善良':'邪恶'}</span></div>)}</div>{normal<7&&<Alert>这是 5–6 人局。首夜不自动提供常规互认与三个伪装信息。</Alert>}</div></Modal>}{selectedSeat&&<Modal title={`${selectedSeat.index} 号 · 配置身份`} onClose={()=>setSelected(undefined)} footer={<Button variant="primary" onClick={()=>setSelected(undefined)}>完成</Button>}><SetupRow key={selectedSeat.id} seat={selectedSeat} game={g} run={run} busy={busy}/></Modal>}{traveller&&<TravellerForm script={g.script} busy={busy} run={run} onClose={()=>setTraveller(false)}/>}</div>;
}
function SetupRow({seat:s,game:g,run,busy}:{seat:Seat;game:Game;run:Run;busy:boolean}){const roles=s.traveller?availableTravellerRoles(g.script):g.script.roles.filter(r=>!r.unresolved&&!['traveller','fabled','loric'].includes(r.team));const role=findRole(g.script,s.roleId);return <fieldset disabled={busy} className="seat-config-row setup-seat-editor"><div className="seat-name-cell"><span className="seat-number">{String(s.index).padStart(2,'0')}</span><input aria-label={`${s.index} 号昵称`} key={`${s.id}-${s.name}`} defaultValue={s.name} maxLength={40} onBlur={e=>{if(e.target.value!==s.name)void run('seat',{id:s.id,patch:{name:e.target.value}});}}/>{s.traveller&&<small className="gold">旅行者</small>}</div><div className="role-select-cell"><RoleToken small role={role}/><div><label>真实角色（仅说书人）<RoleSelect roles={roles} value={s.roleId} onChange={id=>{if(!id)return;const r=findRole(g.script,id)!;const alignment=defaultAlignment(r.team);void run('seat',{id:s.id,patch:{roleId:id,shownRoleId:id,alignment,shownAlignment:alignment}});}}/></label><select aria-label="真实阵营" value={s.alignment} onChange={e=>run('seat',{id:s.id,patch:{alignment:e.target.value}})}><option value="good">善良</option><option value="evil">邪恶</option></select></div></div><div className="role-select-cell"><div><label>展示身份（玩家收到）<RoleSelect roles={roles} value={s.shownRoleId} onChange={id=>{if(id)void run('seat',{id:s.id,patch:{shownRoleId:id}});}}/></label><select aria-label="展示阵营" value={s.shownAlignment} onChange={e=>run('seat',{id:s.id,patch:{shownAlignment:e.target.value}})}><option value="good">告知善良</option><option value="evil">告知邪恶</option></select></div></div></fieldset>;}
export function TravellerForm({script,run,onClose,busy}:{script:Script;run:Run;onClose:()=>void;busy:boolean}){const roles=availableTravellerRoles(script);const [name,setName]=useState(''),[roleId,setRole]=useState(()=>roles.find(r=>r.id==='scapegoat')?.id??roles[0]?.id??''),[alignment,setAlignment]=useState('good');return <Modal title="添加旅行者" onClose={onClose} footer={<Button variant="primary" disabled={busy||!roles.some(r=>r.id===roleId)} onClick={async()=>{if(await run('add_traveller',{name,roleId,alignment}))onClose();}}>加入城镇</Button>}><div className="stack"><Field label="昵称"><input value={name} onChange={e=>setName(e.target.value)} maxLength={40}/></Field><Field label="公开角色"><RoleSelect roles={roles} empty={false} value={roleId} onChange={setRole}/></Field><Field label="真实阵营（只告知本人）"><select value={alignment} onChange={e=>setAlignment(e.target.value)}><option value="good">善良</option><option value="evil">邪恶</option></select></Field><Alert>旅行者身份公开、阵营私密。不占普通角色配置；放逐使用独立流程。</Alert></div></Modal>;}

export function FabledRules({game:g,run,busy}:{game:Game;run:Run;busy:boolean}){const roles=g.script.roles.filter(r=>r.team==='fabled'||r.team==='loric');if(!roles.length)return null;return <section className="fabled-rules"><h3>本局启用的传奇 / 奇遇规则</h3><p className="muted small">只勾选本局实际启用的规则，不占玩家座位。具体效果手动裁定。</p><div className="chips">{roles.map(r=><button key={r.id} disabled={busy} className={`chip ${(g.fabled??[]).includes(r.id)?'gold':''}`} title={r.ability} onClick={()=>run('fabled',{roles:(g.fabled??[]).includes(r.id)?g.fabled.filter(id=>id!==r.id):[...(g.fabled??[]),r.id]})}>{(g.fabled??[]).includes(r.id)?'✓ ':''}{r.name}</button>)}</div></section>;}
