import { useEffect, useRef, useState } from 'react';
import { GitBranch, Mail } from 'lucide-react';
import { Alert, Button, Field } from './ui';
import { config, redirectUrl, supabase } from '../lib/supabase';
import { useApp } from '../lib/context';
export function AuthPanel(){const {user}=useApp();const [email,setEmail]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[token,setToken]=useState('');const sb=supabase();
 async function login(provider:'github'|'email'){setBusy(true);setMessage('');try{if(!sb)throw new Error('请先连接 Supabase。');if(provider==='github'){const {error}=await sb.auth.signInWithOAuth({provider:'github',options:{redirectTo:redirectUrl()}});if(error)throw error;}else{if(!email.includes('@'))throw new Error('请输入有效邮箱。');const {error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:redirectUrl(),captchaToken:token||undefined}});if(error)throw error;setMessage('登录链接已发送，请在此浏览器打开邮件中的链接。');}}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className="stack">{user&&!user.is_anonymous?<Alert kind="success">已登录：{user.email||'GitHub 账号'}</Alert>:<><p className="muted">说书人登录后可跨设备恢复房间。玩家通过匿名身份加入，无需邮箱。</p>{user?.is_anonymous&&<Alert>当前为匿名玩家。改用其他账号后，原座位需要由说书人重新绑定。</Alert>}<Button disabled={busy||!sb} onClick={()=>login('github')}><GitBranch size={18}/> 使用 GitHub 登录</Button><div className="divider-text">或通过邮箱</div><Field label="邮箱"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></Field><Captcha onToken={setToken}/><Button variant="primary" disabled={busy||!sb} onClick={()=>login('email')}><Mail size={17}/> 发送登录链接</Button></>}{message&&<Alert>{message}</Alert>}</div>;
}
declare global {interface Window {turnstile?:{render:(el:HTMLElement,options:Record<string,unknown>)=>string;remove:(id:string)=>void};}}
export function Captcha({onToken}:{onToken:(s:string)=>void}){const ref=useRef<HTMLDivElement>(null);const callback=useRef(onToken);callback.current=onToken;const sitekey=config().turnstile;useEffect(()=>{if(!sitekey)return;let widget:string|undefined;let stopped=false;const render=()=>{if(!stopped&&ref.current&&window.turnstile)widget=window.turnstile.render(ref.current,{sitekey,theme:'dark',callback:(v:string)=>callback.current(v),'expired-callback':()=>callback.current('')});};const existing=document.querySelector<HTMLScriptElement>('#turnstile-script');let script=existing;if(window.turnstile)render();else if(existing)existing.addEventListener('load',render);else{script=document.createElement('script');script.id='turnstile-script';script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.addEventListener('load',render);document.head.appendChild(script);}return ()=>{stopped=true;script?.removeEventListener('load',render);if(widget)window.turnstile?.remove(widget);};},[sitekey]);return sitekey?<div ref={ref} className="captcha"/>:null;}
