import type { Role } from '../lib/domain';
import { RoleToken } from './ui';
import { artUrl, phaseArt } from '../lib/art';
import { Moon, Sun, Skull, Vote, Crown, UserRound } from 'lucide-react';
import type { ReactNode, CSSProperties } from 'react';
import { phaseLabel } from '../lib/storage';
export interface DisplaySeat {id:string;index:number;name:string;role?:string;roleData?:Role;alignment?:string;alive:boolean;voteAvailable:boolean;left:boolean;marks?:string[];traveller?:boolean;}
export function TownBoard({seats,phase,round,selected,onSelect,list=false,centerAction,winner}:{seats:DisplaySeat[];phase:string;round:number;selected?:string;onSelect?:(id:string)=>void;list?:boolean;centerAction?:ReactNode;winner?:string}){return <div className={`town-board ${list?'list-view':''}`}><div className="seat-ring" style={{'--seat-size':seats.length>15?'68px':seats.length>10?'82px':'102px'} as CSSProperties}><div className="orbit"/><div className="town-center"><img className="town-phase-art" src={phaseArt(phase)||artUrl('art/brand/clocktower-emblem.webp')} alt="" width={120} height={70} decoding="async"/>{phase==='night'?<Moon size={42}/>:phase==='ended'?<Crown size={42}/>:<Sun size={42}/>}<h2>{phaseLabel(phase,round)}</h2><p>{phase==='ended'?winner:`存活 ${seats.filter(s=>s.alive&&!s.left).length} 人`}</p>{centerAction}</div>{seats.map((s,i)=>{const angle=(i/Math.max(seats.length,1))*Math.PI*2-Math.PI/2;return <button key={s.id} className={`seat-node ${s.alignment||'neutral'} ${!s.alive?'dead':''} ${s.left?'left':''} ${selected===s.id?'selected':''} ${s.traveller?'traveller-seat':''}`} style={{'--x':`${50+40*Math.cos(angle)}%`,'--y':`${50+40*Math.sin(angle)}%`} as CSSProperties} onClick={()=>onSelect?.(s.id)} aria-label={`${s.index} 号 ${s.name} ${s.role||''} ${s.left?'离场':s.alive?'存活':'死亡'}`}><span className="seat-index">{String(s.index).padStart(2,'0')}{!s.alive&&<Skull size={13}/>}</span><span className="seat-art">{s.roleData?<RoleToken role={s.roleData} alignment={s.alignment}/>:<UserRound size={30}/>}</span><strong>{s.name}</strong><span className="seat-role">{s.role||(s.left?'已离场':s.alive?'存活':'死亡')}</span><span className="seat-flags">{s.traveller&&<small>旅</small>}{!s.alive&&<Vote size={13} className={s.voteAvailable?'gold':'muted'}/>}</span>{s.marks&&s.marks.length>0&&<span className="seat-markers">{s.marks.slice(0,2).map((m,i)=><small key={i}>{m}</small>)}{s.marks.length>2&&<small>+{s.marks.length-2}</small>}</span>}</button>;})}</div></div>;}


